app:
  mode: ${APP_MODE}
auth:
  jwt:
    user_access_token_signing_key: ${USER_ACCESS_TOKEN_SIGNING_KEY}
  request_signing_key: ${REQUEST_SIGNING_KEY}
http_server:
  port: ${HTTP_SERVER_PORT}
mongo:
  connection_string: ${NEWSFEED_DATABASE_CONNECTION_STRING}
newsfeed_event:
  username: ${KAFKA_USERNAME}
  password: ${KAFKA_PASSWORD}
  bootstrap_servers: ${KAFKA_BOOTSTRAP_SERVERS}
  ssl_root_ca_path: ${KAFKA_SSL_ROOT_CERT}
player_service:
  host: ${PLAYER_SERVICE_GRPC_HOST}
