services:
  nginx:
    image: nginx:1.27-alpine
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /trinquet/conf/nginx/init.conf:/etc/nginx/conf.d/default.conf:ro
      - /trinquet/.data/certbot/conf:/etc/letsencrypt/:ro
      - /trinquet/.data/certbot/webroot:/var/www/certbot/:ro

  certbot:
    image: certbot/certbot:latest
    container_name: certbot
    volumes:
      - /trinquet/.data/certbot/conf:/etc/letsencrypt/:rw
      - /trinquet/.data/certbot/webroot:/var/www/certbot/:rw
    healthcheck:
      test: "exit 0"
