app:
  mode: ${APP_MODE}
auth:
  jwt:
    user_access_token_signing_key: ${USER_ACCESS_TOKEN_SIGNING_KEY}
  request_signing_key: ${REQUEST_SIGNING_KEY}
http_server:
  port: ${HTTP_SERVER_PORT}
grpc_server:
  port: ${GRPC_SERVER_PORT}
psql:
  connection_string: ${PLAYER_DATABASE_CONNECTION_STRING}
neo4j:
  uri: ${USER_RELATION_DATABASE_URI}
  database: ${USER_RELATION_DATABASE_NAME}
  username: ${USER_RELATION_DATABASE_USERNAME}
  password: ${USER_RELATION_DATABASE_PASSWORD}
  ssl_root_cert: ${USER_RELATION_DATABASE_SSL_ROOT_CERT}
