REVOKE USAGE ON SCHEMA chat_service FROM "service-user";
ALTER DEFAULT PRIVILEGES IN SCHEMA chat_service REVOKE SELECT, UPDATE, INSERT, DELETE ON TABLES FROM "service-user";
--DROP SCHEMA IF EXISTS chat_service CASCADE;
