REVOKE USAGE ON SCHEMA court_service FROM "service-user";
ALTER DEFAULT PRIVILEGES IN SCHEMA court_service REVOKE SELECT, UPDATE, INSERT, DELETE ON TABLES FROM "service-user";
--DROP SCHEMA IF EXISTS court_service CASCADE;
