REVOKE USAGE ON SCHEMA player_service FROM "service-user";
ALTER DEFAULT PRIVILEGES IN SCHEMA player_service REVOKE SELECT, UPDATE, INSERT, DELETE ON TABLES FROM "service-user";
--DROP SCHEMA IF EXISTS player_service CASCADE;
