app:
  mode: ${APP_MODE}
auth:
  jwt:
    user_access_token_signing_key: ${USER_ACCESS_TOKEN_SIGNING_KEY}
  request_signing_key: ${REQUEST_SIGNING_KEY}
http_server:
  port: ${HTTP_SERVER_PORT}
psql:
  connection_string: ${DATABASE_CONNECTION_STRING}
